In [1]:
#Get dependencies
import pandas as pd

#2010 Health Data

In [2]:
#Get 2010 health data from csv file
hc_data = pd.read_csv ('Resources/Pew_Millennials_Data.csv')

hc_df = pd.DataFrame(hc_data)

,resp,comp,fproj,timezone,sfips,smsa,qcendiv,sstate,phtype,susr,...,fdate,fdow,phoneuse,adults,psadjust,puadjust,wt1,weight,q46x,agegroups
0,2,1,4968,1,36061,35620.0,2,NY,1.0,U,...,100114,5,2,3,2,1.0,2.0,0.543,0,29
1,4,1,4968,2,31055,36540.0,4,NE,1.0,U,...,100114,5,2,2,2,1.0,2.0,1.488,1,45
2,5,1,4968,1,18023,0.0,3,IN,1.0,R,...,100114,5,2,2,2,1.0,2.0,0.972,0,45
3,6,1,4968,1,18057,26900.0,3,IN,0.0,S,...,100114,5,2,2,2,1.0,2.0,1.844,0,97
4,7,1,4968,1,51065,16820.0,5,VA,1.0,S,...,100114,5,2,2,2,1.0,2.0,1.282,0,64
5,8,1,4968,1,24003,12580.0,5,MD,1.0,S,...,100114,5,2,2,2,1.0,2.0,0.833,0,0
6,10,1,4968,1,42101,37980.0,2,PA,0.0,U,...,100114,5,1,1,1,2.0,2.0,1.255,0,64
7,13,1,4968,1,37007,16740.0,5,NC,1.0,S,...,100114,5,2,1,1,1.0,1.0,0.887,1,64
8,14,1,4968,2,12091,18880.0,5,FL,1.0,S,...,100114,5,2,2,2,1.0,2.0,1.625,0,64
9,15,1,4968,2,29097,27900.0,4,MO,1.0,U,...,100114,5,2,1,1,1.0,1.0,0.706,0,64

In [7]:
#Pull only health answers with the response ID and age
hc_df = hc_df[['resp','q7.1','q7.2','q7.3','q7.4','q7.5','age','health']]

In [11]:
#Questions 7.1 - 7.5 respondent ranked which generation is healthier (= 35)
healthier_df = hc_df.loc[(hc_df['q7.1']==35) | (hc_df['q7.2']==35) | (hc_df['q7.3']==35) | \
                  (hc_df['q7.4']==35) | (hc_df['q7.5']==35)]

        resp  q7.1  q7.2  q7.3  q7.4  q7.5  age  health
129      158    27    35     0     0     0   68       1
305      396     1    35     0     0     0   57       1
331      428    35     0     0     0     0   21       1
980   100598    16    17    35     0     0   40       2
1083  100834    29    35     0     0     0   22       1
1503  200047    12    35     0     0     0   28       1

In [15]:
#Count how many millennials (ages 13 - 29) were insured in 2010
insured_df = hc_df.loc[(hc_df['health']==1) & (hc_df['age']>=13) & (hc_df['age']<=29)].sum()
uninsured_df = hc_df.loc[(hc_df['health']==2) & (hc_df['age']>=13) & (hc_df['age']<=29)].sum()

#2017 Health Data

In [22]:
#Get 2017 health data from csv file
health_data = pd.read_csv ('Resources/personsx.csv')

health_df = pd.DataFrame(health_data)

In [25]:
health_df.head(10)

,FPX,AGE_CHG,INTV_QRT,SEX,NOWAF,FSPOUS2,COHAB1,COHAB2,FCOHAB3,ASTATFLG,...,EDUC1,ERNYR_P,ARMFTM7P,ARMFTM1P,ARMFTM2P,ARMFTM3P,ARMFTM4P,ARMFTM5P,ARMFTM6P,ENGLANG
0,1,NaN,1,2,NaN,NaN,NaN,NaN,NaN,1.0,...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,1,NaN,1,2,2.0,2.0,NaN,NaN,NaN,2.0,...,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,2,NaN,1,1,2.0,1.0,NaN,NaN,NaN,0.0,...,15,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,3,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,1,NaN,1,1,2.0,2.0,NaN,NaN,NaN,1.0,...,21,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
5,2,NaN,1,2,2.0,1.0,NaN,NaN,NaN,2.0,...,18,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
6,3,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
7,4,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
8,1,NaN,1,1,2.0,2.0,NaN,NaN,NaN,1.0,...,16,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
9,2,NaN,1,2,2.0,1.0,NaN,NaN,NaN,2.0,...,15,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [31]:
#Pull only relevant health answers with the age
health_stat_df1 = health_df.loc[:,'AGE_P','SEX','PLAWKNOW','LAHCA1','LAHCA2','LAHCA17','LAHCA18', \
                                'LAUNIT29','LAUNIT30','LAUNIT33', 'LACHRONR','PDMED12M','PNMED12M']

health_stat_df2 = health_df.loc[:,'AGE_P','SEX','PHOSPYR2','HOSPNO','HPNITE','PHCHM2W','PHCHMN2W', \
               'PHCPH2WR','PHCPHN2W','PHCDV2W','PHCDVN2W','P10DVYR']

ins_cvg_df1 = health_df.loc[:,'AGE_P','SEX','NOTCOV','COVER','PLNWRKS1','HICOSTR1','PRPOLH2','HILAST2','HISTOP1','HISTOP2', \
                       'HISTOP3','HISTOP4','HISTOP5','HISTOP6','HISTOP10','HISTOP11','HISTOP12', \
                       'HISTOP13','HISTOP14']

ins_cvg_df2 = health_df.loc[:,'AGE_P','SEX','HINOTYR','HINOTMYR','FHICHNG','FHIKDBA','FHIKDBB', \
                       'FHIKDBC','FHIKDBD','FHIKDBF','FHIKDBH','FHIKDBI','FHIKDBK','FINCINT','HIKINDNK','HCSPFYR', \
                       'MEDBNOP','MEDBILL','MEDBPAY']


stat_df = health_df.loc[:,'AGE_P','SEX','PHSTAT','PLBORN','YRSINUS','CITIZENP','EDUC1']

TypeError: unhashable type: 'slice'